import { Message, Room, UserProfile } from '../types';

export const INITIAL_DEMO_USERS: UserProfile[] = [
  {
    uid: 'user_vishal',
    displayName: 'Vishal Gangwar',
    email: 'vishal.gangwar@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    statusText: 'Software Development Intern • Task-04 Submission 🎓',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_aarav',
    displayName: 'Aarav Sharma',
    email: 'aarav.sharma@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    statusText: 'Lead Backend Architect • WebSocket & DB scaling ⚡',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_priya',
    displayName: 'Priya Patel',
    email: 'priya.patel@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    statusText: 'Product Design Lead • Polishing WhatsApp UI/UX 🎨',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_rohan',
    displayName: 'Rohan Verma',
    email: 'rohan.verma@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    statusText: 'Cloud & DevOps • CI/CD & Firebase Hosting 🚀',
    isOnline: false,
    lastSeen: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
  },
  {
    uid: 'user_ananya',
    displayName: 'Ananya Iyer',
    email: 'ananya.iyer@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    statusText: 'Frontend Engineer • React 19 & Tailwind v4 💻',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_aditya',
    displayName: 'Aditya Nair',
    email: 'aditya.nair@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    statusText: 'Security & QA • Firestore ABAC verification 🛡️',
    isOnline: false,
    lastSeen: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
  },
  {
    uid: 'user_neha',
    displayName: 'Neha Gupta',
    email: 'neha.gupta@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    statusText: 'Engineering Manager • Sprint reviews & mentorship 🌟',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_vikram',
    displayName: 'Vikram Malhotra',
    email: 'vikram.malhotra@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    statusText: 'VP of Engineering • Mumbai Chapter 🇮🇳 • Available',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_kavya',
    displayName: 'Kavya Subramanian',
    email: 'kavya.subramanian@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    statusText: 'Senior Product Designer • Chennai 🎨 • At design review',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_arjun',
    displayName: 'Arjun Singhania',
    email: 'arjun.singhania@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=150&auto=format&fit=crop&q=80',
    statusText: 'Staff Frontend Architect • Delhi NCR ⚡ • Coding in React',
    isOnline: false,
    lastSeen: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
  },
  {
    uid: 'user_divya',
    displayName: 'Divya Ranganathan',
    email: 'divya.ranganathan@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    statusText: 'Site Reliability Engineer • Hyderabad ☁️ • On call',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_tanmay',
    displayName: 'Tanmay Deshmukh',
    email: 'tanmay.deshmukh@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    statusText: 'Lead Mobile Engineer • Pune 📱 • Chai break ☕',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_meera',
    displayName: 'Meera Nambiar',
    email: 'meera.nambiar@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1534751516642-a1714f5a593e?w=150&auto=format&fit=crop&q=80',
    statusText: 'AI/ML Research Scientist • Kochi 🤖 • In a meeting',
    isOnline: false,
    lastSeen: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    uid: 'user_rahul',
    displayName: 'Rahul Choudhury',
    email: 'rahul.choudhury@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1513956589380-bad6acb9b9d4?w=150&auto=format&fit=crop&q=80',
    statusText: 'DevOps & Cloud Security • Kolkata 🛡️ • Urgent calls only',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_shreya',
    displayName: 'Shreya Kulkarni',
    email: 'shreya.kulkarni@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
    statusText: 'Engineering Team Lead • Bengaluru 🌸 • Busy',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_siddharth',
    displayName: 'Siddharth Roy',
    email: 'siddharth.roy@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    statusText: 'Backend Engineer • Gurgaon 💻 • Hey there! I am using WhatsApp',
    isOnline: false,
    lastSeen: new Date(Date.now() - 120 * 60 * 1000).toISOString(),
  },
  {
    uid: 'user_alex',
    displayName: 'Alex Chen',
    email: 'alex.chen@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80',
    statusText: 'Core Platform Tech Lead 🛠️',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
  {
    uid: 'user_maya',
    displayName: 'Maya Lin',
    email: 'maya.lin@pulsechat.io',
    photoURL: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    statusText: 'Design Systems Architect 📐',
    isOnline: true,
    lastSeen: new Date().toISOString(),
  },
];

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room_general',
    type: 'channel',
    name: 'general',
    description: 'Company-wide updates, welcome notes, and team-wide announcements.',
    icon: 'Megaphone',
    createdBy: 'user_neha',
    members: [
      'user_vishal',
      'user_aarav',
      'user_priya',
      'user_rohan',
      'user_ananya',
      'user_aditya',
      'user_neha',
      'user_vikram',
      'user_kavya',
      'user_arjun',
      'user_divya',
      'user_tanmay',
      'user_meera',
      'user_rahul',
      'user_shreya',
      'user_siddharth',
      'user_alex',
      'user_maya',
    ],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessageSnippet: 'Welcome everyone to the new PulseChat workspace! 🚀',
    lastMessageAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    lastMessageSenderId: 'user_aarav',
  },
  {
    id: 'room_engineering',
    type: 'channel',
    name: 'engineering',
    description: 'Architecture decisions, pull requests, CI/CD, and technical deep dives.',
    icon: 'Code2',
    createdBy: 'user_aarav',
    members: [
      'user_vishal',
      'user_aarav',
      'user_rohan',
      'user_ananya',
      'user_aditya',
      'user_vikram',
      'user_arjun',
      'user_divya',
      'user_siddharth',
      'user_alex',
    ],
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessageSnippet: 'Real-time WebSocket and onSnapshot sync are performing sub-50ms!',
    lastMessageAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    lastMessageSenderId: 'user_aarav',
  },
  {
    id: 'room_mumbai',
    type: 'channel',
    name: 'mumbai-devs',
    description: 'Mumbai chapter • Bandra-Kurla & Powai tech circle, fintech & UPI systems 🇮🇳',
    icon: 'Coffee',
    createdBy: 'user_vikram',
    members: [
      'user_vishal',
      'user_vikram',
      'user_tanmay',
      'user_priya',
      'user_divya',
      'user_rahul',
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessageSnippet: 'Powai developers meet is confirmed for Saturday at 5 PM! ☕',
    lastMessageAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    lastMessageSenderId: 'user_vikram',
  },
  {
    id: 'room_chai',
    type: 'channel',
    name: 'chai-pe-charcha',
    description: 'Cutting chai, samosa breaks, cricket matches, and casual watercooler banter ☕🏏',
    icon: 'Coffee',
    createdBy: 'user_tanmay',
    members: [
      'user_vishal',
      'user_tanmay',
      'user_kavya',
      'user_arjun',
      'user_shreya',
      'user_siddharth',
      'user_ananya',
      'user_rohan',
      'user_aarav',
      'user_priya',
    ],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessageSnippet: 'Anyone up for a quick cutting chai break at the terrace? 🫖',
    lastMessageAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    lastMessageSenderId: 'user_tanmay',
  },
  {
    id: 'room_india_hub',
    type: 'channel',
    name: 'bangalore-hub',
    description: 'Bengaluru engineering chapter, Koramangala & HSR syncs.',
    icon: 'Coffee',
    createdBy: 'user_neha',
    members: [
      'user_vishal',
      'user_aarav',
      'user_priya',
      'user_rohan',
      'user_ananya',
      'user_aditya',
      'user_neha',
      'user_shreya',
    ],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessageSnippet: 'Filter coffee is ready on the 3rd floor lounge ☕',
    lastMessageAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    lastMessageSenderId: 'user_shreya',
  },
  {
    id: 'room_design',
    type: 'channel',
    name: 'design-system',
    description: 'Typography, WhatsApp tokens, dark/light theme, and Figma components.',
    icon: 'Palette',
    createdBy: 'user_priya',
    members: ['user_priya', 'user_kavya', 'user_ananya', 'user_vishal', 'user_maya'],
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessageSnippet: 'WhatsApp green palette (#00a884) & doodle background look amazing! ✨',
    lastMessageAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    lastMessageSenderId: 'user_kavya',
  },
  {
    id: 'dm_vishal_kavya',
    type: 'direct',
    name: 'Kavya Subramanian',
    createdBy: 'user_kavya',
    members: ['user_vishal', 'user_kavya'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessageSnippet: 'The WhatsApp dark theme looks very authentic! Check the attachment.',
    lastMessageAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    lastMessageSenderId: 'user_kavya',
  },
  {
    id: 'dm_vishal_vikram',
    type: 'direct',
    name: 'Vikram Malhotra',
    createdBy: 'user_vikram',
    members: ['user_vishal', 'user_vikram'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessageSnippet: 'Great work on the real-time presence indicators Vishal! 👏',
    lastMessageAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    lastMessageSenderId: 'user_vikram',
  },
  {
    id: 'dm_vishal_tanmay',
    type: 'direct',
    name: 'Tanmay Deshmukh',
    createdBy: 'user_tanmay',
    members: ['user_vishal', 'user_tanmay'],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date().toISOString(),
    lastMessageSnippet: 'Hey Vishal, are we deploying the new build today?',
    lastMessageAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    lastMessageSenderId: 'user_tanmay',
  },
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  room_general: [
    {
      id: 'msg_gen_1',
      roomId: 'room_general',
      senderId: 'user_neha',
      senderName: 'Neha Gupta',
      senderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      text: 'Good morning everyone! A big warm welcome to our engineering team workspace. Please introduce yourselves in the channel!',
      readBy: ['user_neha', 'user_vishal', 'user_aarav', 'user_priya', 'user_vikram', 'user_kavya'],
      createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_gen_2',
      roomId: 'room_general',
      senderId: 'user_vishal',
      senderName: 'Vishal Gangwar',
      senderAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      text: 'Hello team! Excited to work on the real-time sync engine, presence tracking, and WhatsApp UI redesign for Task-04. Looking forward to collaborating with everyone!',
      readBy: ['user_neha', 'user_vishal', 'user_aarav', 'user_priya', 'user_ananya', 'user_vikram'],
      createdAt: new Date(Date.now() - 110 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_gen_3',
      roomId: 'room_general',
      senderId: 'user_vikram',
      senderName: 'Vikram Malhotra',
      senderAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      text: 'Welcome Vishal! Really happy to see our pan-India engineering team expanding across Mumbai, Bengaluru, Delhi, Hyderabad, and Chennai 🇮🇳',
      readBy: ['user_neha', 'user_vishal', 'user_vikram', 'user_kavya'],
      createdAt: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_gen_4',
      roomId: 'room_general',
      senderId: 'user_aarav',
      senderName: 'Aarav Sharma',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      text: 'Welcome everyone to the new PulseChat workspace! 🚀 All features including image uploads, typing indicators, presence, and sound notifications are active.',
      readBy: ['user_aarav', 'user_vishal'],
      createdAt: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    },
  ],
  room_engineering: [
    {
      id: 'msg_eng_1',
      roomId: 'room_engineering',
      senderId: 'user_vishal',
      senderName: 'Vishal Gangwar',
      senderAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      text: 'Hey Aarav, I updated the WebSocket server with an active sendQueue so connection drops are handled without any lost packets.',
      readBy: ['user_vishal', 'user_aarav'],
      createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_eng_2',
      roomId: 'room_engineering',
      senderId: 'user_aarav',
      senderName: 'Aarav Sharma',
      senderAvatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
      text: 'Real-time WebSocket and onSnapshot sync are performing sub-50ms! Great job on the idempotent message handlers.',
      readBy: ['user_vishal', 'user_aarav'],
      createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_eng_3',
      roomId: 'room_engineering',
      senderId: 'user_divya',
      senderName: 'Divya Ranganathan',
      senderAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
      text: 'Production load test passed with 10k simulated concurrent clients without dropping a single WebSocket frame. Latency p99 is under 45ms 🚀',
      readBy: ['user_vishal', 'user_aarav', 'user_divya'],
      createdAt: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    },
  ],
  room_mumbai: [
    {
      id: 'msg_mum_1',
      roomId: 'room_mumbai',
      senderId: 'user_vikram',
      senderName: 'Vikram Malhotra',
      senderAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      text: 'Namaste Mumbai team! We are coordinating the fintech and real-time payment gateway integration from the BKC office.',
      readBy: ['user_vikram', 'user_vishal', 'user_tanmay'],
      createdAt: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_mum_2',
      roomId: 'room_mumbai',
      senderId: 'user_tanmay',
      senderName: 'Tanmay Deshmukh',
      senderAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
      text: 'Super! Mobile SDK is ready with native haptics and instant message previews for Android & iOS.',
      readBy: ['user_vikram', 'user_vishal', 'user_tanmay'],
      createdAt: new Date(Date.now() - 25 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_mum_3',
      roomId: 'room_mumbai',
      senderId: 'user_vikram',
      senderName: 'Vikram Malhotra',
      senderAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      text: 'Powai developers meet is confirmed for Saturday at 5 PM! ☕',
      readBy: ['user_vikram', 'user_vishal'],
      createdAt: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
    },
  ],
  room_chai: [
    {
      id: 'msg_chai_1',
      roomId: 'room_chai',
      senderId: 'user_tanmay',
      senderName: 'Tanmay Deshmukh',
      senderAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
      text: 'Anyone up for a quick cutting chai break at the terrace? 🫖 Special ginger and elaichi chai is brewing!',
      readBy: ['user_tanmay', 'user_vishal', 'user_kavya', 'user_arjun'],
      createdAt: new Date(Date.now() - 18 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_chai_2',
      roomId: 'room_chai',
      senderId: 'user_kavya',
      senderName: 'Kavya Subramanian',
      senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      text: 'Count me in! Also brought some hot Mysore pak from Chennai for the team 😋',
      readBy: ['user_tanmay', 'user_vishal', 'user_kavya'],
      createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_chai_3',
      roomId: 'room_chai',
      senderId: 'user_vishal',
      senderName: 'Vishal Gangwar',
      senderAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      text: 'Joining right now! Perfect timing after finishing the WhatsApp dark mode theme commit 🍵',
      readBy: ['user_tanmay', 'user_vishal'],
      createdAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    },
  ],
  room_design: [
    {
      id: 'msg_des_1',
      roomId: 'room_design',
      senderId: 'user_priya',
      senderName: 'Priya Patel',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      text: 'Color contrast ratios and WhatsApp dark mode tokens are fully accessible! ✨ Here is the preview of the refreshed design tokens.',
      attachment: {
        name: 'whatsapp-theme-tokens.jpg',
        url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=800&auto=format&fit=crop&q=80',
        type: 'image/jpeg',
        size: 245000,
      },
      readBy: ['user_priya', 'user_vishal', 'user_kavya'],
      createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_des_2',
      roomId: 'room_design',
      senderId: 'user_kavya',
      senderName: 'Kavya Subramanian',
      senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      text: 'WhatsApp green palette (#00a884) & doodle background look amazing! ✨ Chat bubbles (#d9fdd3 and #005c4b) have that authentic feel.',
      readBy: ['user_priya', 'user_kavya', 'user_vishal'],
      createdAt: new Date(Date.now() - 35 * 60 * 1000).toISOString(),
    },
  ],
  room_india_hub: [
    {
      id: 'msg_hub_1',
      roomId: 'room_india_hub',
      senderId: 'user_neha',
      senderName: 'Neha Gupta',
      senderAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
      text: 'Team lunch scheduled for this Friday! 🍛 Let me know if anyone has dietary preferences.',
      readBy: ['user_neha', 'user_vishal', 'user_aarav', 'user_priya', 'user_rohan'],
      createdAt: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_hub_2',
      roomId: 'room_india_hub',
      senderId: 'user_shreya',
      senderName: 'Shreya Kulkarni',
      senderAvatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
      text: 'Filter coffee is ready on the 3rd floor lounge ☕',
      readBy: ['user_neha', 'user_shreya', 'user_vishal'],
      createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    },
  ],
  dm_vishal_kavya: [
    {
      id: 'msg_dm_kavya_1',
      roomId: 'dm_vishal_kavya',
      senderId: 'user_kavya',
      senderName: 'Kavya Subramanian',
      senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      text: 'Hi Vishal! I reviewed the latest WhatsApp UI layout and it looks incredible.',
      readBy: ['user_kavya', 'user_vishal'],
      createdAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_dm_kavya_2',
      roomId: 'dm_vishal_kavya',
      senderId: 'user_vishal',
      senderName: 'Vishal Gangwar',
      senderAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      text: 'Thanks Kavya! Working on ensuring the doodle background and dark theme bubble colors match WhatsApp Web pixel-by-pixel.',
      readBy: ['user_kavya', 'user_vishal'],
      createdAt: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_dm_kavya_3',
      roomId: 'dm_vishal_kavya',
      senderId: 'user_kavya',
      senderName: 'Kavya Subramanian',
      senderAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
      text: 'The WhatsApp dark theme looks very authentic! Check the attachment.',
      readBy: ['user_kavya', 'user_vishal'],
      createdAt: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    },
  ],
  dm_vishal_vikram: [
    {
      id: 'msg_dm_vikram_1',
      roomId: 'dm_vishal_vikram',
      senderId: 'user_vikram',
      senderName: 'Vikram Malhotra',
      senderAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
      text: 'Great work on the real-time presence indicators Vishal! 👏 The WebSocket broadcast is super responsive.',
      readBy: ['user_vikram', 'user_vishal'],
      createdAt: new Date(Date.now() - 22 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_dm_vikram_2',
      roomId: 'dm_vishal_vikram',
      senderId: 'user_vishal',
      senderName: 'Vishal Gangwar',
      senderAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      text: 'Thank you Vikram sir! Added the fallback channels and localStorage sync as well.',
      readBy: ['user_vikram', 'user_vishal'],
      createdAt: new Date(Date.now() - 20 * 60 * 1000).toISOString(),
    },
  ],
  dm_vishal_tanmay: [
    {
      id: 'msg_dm_tanmay_1',
      roomId: 'dm_vishal_tanmay',
      senderId: 'user_tanmay',
      senderName: 'Tanmay Deshmukh',
      senderAvatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
      text: 'Hey Vishal, are we deploying the new build today?',
      readBy: ['user_tanmay', 'user_vishal'],
      createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    },
    {
      id: 'msg_dm_tanmay_2',
      roomId: 'dm_vishal_tanmay',
      senderId: 'user_vishal',
      senderName: 'Vishal Gangwar',
      senderAvatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
      text: 'Yes Tanmay! Verified all test cases and compile status is clean.',
      readBy: ['user_tanmay', 'user_vishal'],
      createdAt: new Date(Date.now() - 40 * 60 * 1000).toISOString(),
    },
  ],
};
